const content = {
  cs: {
    home: {
      eyebrow: 'Česko × Chorvatsko',
      title: 'Váš spolehlivý partner pro podnikání, investice a život v Chorvatsku.',
      lead: 'Pomáháme českým občanům, podnikatelům a investorům jednodušeji uskutečnit jejich plány v Chorvatsku. Propojíme vás s prověřenými odborníky a provedeme vás celým procesem.',
      trust: 'Osobní přístup · místní znalost · prověření partneři',
      categories: [
        ['Nemovitosti', 'Podpora při koupi a koordinace dokumentace.'],
        ['Podnikání', 'Praktická pomoc při vstupu na chorvatský trh.'],
        ['Administrativa', 'Jistota v postupech, formulářích a komunikaci.'],
        ['Prověření partneři', 'Síť odborníků pro každý krok vašeho projektu.'],
      ],
      introTitle: 'Méně nejistoty. Více jasných kroků.',
      introText: 'CROBIZ spojuje znalost českého a chorvatského prostředí s osobním vedením. Získáte jeden spolehlivý kontaktní bod, srozumitelnou komunikaci a koordinaci lidí, které váš záměr skutečně potřebuje.',
      servicesTitle: 'Podpora přesně tam, kde ji potřebujete',
      whyTitle: 'Proč právě Chorvatsko?',
      whyText: 'Bezpečná evropská země s eurem, stabilním trhem, silným turismem a výjimečnou kvalitou života.',
      processTitle: 'Od první otázky k hotovému řešení',
      process: [['01', 'Úvodní konzultace', 'Poznáme váš cíl, situaci a priority.'], ['02', 'Jasný plán', 'Navrhneme kroky, dokumentaci a správné odborníky.'], ['03', 'Koordinace', 'Propojíme všechny strany a hlídáme průběh.'], ['04', 'Dlouhodobá podpora', 'Zůstáváme vaším partnerem i po dokončení.']],
    },
    about: {
      eyebrow: 'O CROBIZ', title: 'Specializované poradenství mezi Českem a Chorvatskem.',
      lead: 'CROBIZ je specializovaná poradenská společnost poskytující podporu českým občanům, podnikatelům a investorům v Chorvatsku.',
      storyTitle: 'O společnosti CROBIZ',
      story: 'Zakladatelkou CROBIZ je Ivana Pisac, která díky výborné znalosti chorvatského a českého jazyka i podnikatelského prostředí obou zemí pomáhá klientům koordinovat administrativní a obchodní procesy.',
      values: [['Dva jazyky, jedno porozumění', 'Plynulá komunikace v češtině a chorvatštině bez zbytečných nedorozumění.'], ['Individuální přístup', 'Řešení přizpůsobené vašemu cíli, rozpočtu a časovým možnostem.'], ['Profesionální koordinace', 'Přehledné kroky, průběžné informace a odpovědnost za komunikaci.'], ['Dlouhodobé vztahy', 'Nejde nám o jednorázovou službu, ale o partnerství založené na důvěře.']],
      networkTitle: 'Síť prověřených partnerů po celém Chorvatsku',
    },
    how: {
      eyebrow: 'Jak spolupracujeme', title: 'Jasný postup od první konzultace po dlouhodobou podporu.',
      lead: 'Každou spolupráci stavíme na srozumitelných krocích, pravidelné komunikaci a koordinaci správných odborníků.',
    },
    services: {
      eyebrow: 'Služby', title: 'Komplexní podpora pro vaše plány v Chorvatsku.',
      lead: 'Od prvního průzkumu až po koordinaci konkrétního procesu. Vybereme správný postup a propojíme vás s potřebnými odborníky.',
      groups: [
        ['Podnikání v Chorvatsku', ['Informace o podnikatelském prostředí', 'Pomoc se založením společnosti nebo živnosti', 'Administrativní podpora', 'Propojení s účetními službami', 'Pomoc při otevření podnikatelského účtu']],
        ['Nemovitosti', ['Podpora při koupi nemovitosti', 'Kontrola a koordinace procesu', 'Pomoc s dokumentací', 'Komunikace s účastníky transakce']],
        ['Administrativní podpora', ['Komunikace s institucemi', 'Pomoc s dokumentací a formuláři', 'Koordinace postupů', 'Průběžné vysvětlení dalších kroků']],
        ['Právní a účetní zprostředkování', ['Propojení s advokáty a notáři', 'Propojení s účetními a daňovými poradci', 'Koordinace komunikace během procesu']],
        ['Pojištění', ['Pojištění nemovitostí', 'Pojištění vozidel a cestovní pojištění', 'Zdravotní a podnikatelské pojištění']],
        ['Turismus', ['Pomoc s kategorizací apartmánů', 'Administrativní podpora', 'Pomoc při zahájení turistické činnosti']],
        ['Překlady a komunikace', ['Chorvatština–čeština a čeština–chorvatština', 'Obchodní komunikace', 'Podpora při jednání s institucemi']],
      ],
      disclaimerTitle: 'Důležité upozornění',
      disclaimer: 'CROBIZ neposkytuje právní ani účetní služby. Klienty propojuje s prověřenými advokáty, notáři, účetními a dalšími odborníky a koordinuje vzájemnou komunikaci.',
      partners: ['Advokáti', 'Notáři', 'Účetní', 'Daňoví poradci', 'Architekti', 'Projektanti', 'Geodeti', 'Stavební firmy', 'Realitní makléři', 'Pojišťovny', 'Soudní tlumočníci'],
    },
    why: {
      eyebrow: 'Proč Chorvatsko', title: 'Stabilní evropské prostředí s výjimečným potenciálem.',
      lead: 'Chorvatsko kombinuje bezpečí Evropské unie, euro, silnou turistickou ekonomiku a životní styl, který dlouhodobě přitahuje české občany i investory.',
      reasons: [['Člen Evropské unie', 'Společný právní a ekonomický rámec usnadňuje pohyb osob, kapitálu i podnikání.'], ['Euro jako měna', 'Jednodušší platby, plánování investic a menší kurzové riziko.'], ['Stabilní trh', 'Předvídatelné prostředí a rostoucí zájem zahraničních investorů.'], ['Atraktivní investice', 'Příležitosti v nemovitostech, turismu, službách a lokálním podnikání.'], ['Rozvinutý turismus', 'Silná mezinárodní poptávka a dlouhodobá známost destinace.'], ['Výborná dostupnost', 'Silniční i letecké spojení s Českou republikou během celého roku.'], ['Kvalita života', 'Bezpečí, příroda, klima, gastronomie a blízkost moře.']],
      sectorsTitle: 'Příležitosti, které dávají smysl',
      sectors: ['Rezidenční nemovitosti', 'Turistické ubytování', 'Služby a obchod', 'Lokální partnerství'],
    },
    faq: {
      eyebrow: 'Časté otázky', title: 'Odpovědi, které vám pomohou začít.',
      lead: 'Každý případ je jiný, ale tyto odpovědi vám poskytnou základní orientaci.',
      items: [
        ['Jak koupit nemovitost v Chorvatsku?', 'Proces začíná definováním rozpočtu a požadavků, pokračuje prověřením nemovitosti a dokumentace a končí smlouvou, platbou a zápisem vlastnictví. CROBIZ koordinuje komunikaci a propojí vás s příslušným advokátem nebo notářem.'],
        ['Jak založit firmu?', 'Podle vašich cílů se zvolí vhodná právní forma, připraví dokumentace, provede registrace a otevře účet. Pomůžeme vám zorganizovat kroky a najít účetního.'],
        ['Jak dlouho proces trvá?', 'Doba závisí na typu služby, připravenosti dokumentace a institucích. Po úvodní konzultaci vám dáme realistický časový rámec.'],
        ['Lze vše vyřídit na dálku?', 'Mnoho kroků lze řešit online nebo prostřednictvím plné moci. Upozorníme vás, pokud je osobní přítomnost nutná nebo výhodná.'],
        ['V jakém jazyce komunikujete?', 'Komunikujeme česky, chorvatsky a anglicky. S odborníky a institucemi koordinujeme komunikaci tak, abyste vždy rozuměli dalšímu kroku.'],
        ['Pracujete v celém Chorvatsku?', 'Ano. Díky síti partnerů pomáháme klientům v různých částech Chorvatska, vždy podle konkrétního projektu a dostupnosti odborníků.'],
      ],
    },
    contact: { eyebrow: 'Kontakt', title: 'Promluvme si o vašem plánu.', lead: 'Popište nám stručně svou situaci. Ozveme se, upřesníme potřeby a navrhneme nejlepší další krok.', hours: 'Pondělí–pátek · 9:00–17:00', response: 'Odpovídáme zpravidla do jednoho pracovního dne.' },
    blog: { eyebrow: 'Průvodce Chorvatskem', title: 'Praktické informace pro chytrá rozhodnutí.', lead: 'Srozumitelné články o nemovitostech, podnikání, administrativě a životě v Chorvatsku.', posts: [['koupe-nemovitosti', 'Koupě nemovitosti v Chorvatsku: první kroky', 'Nemovitosti', 'Co si ujasnit před hledáním a jak probíhá bezpečný proces koupě.'], ['zalozeni-firmy', 'Jak založit firmu v Chorvatsku', 'Podnikání', 'Přehled základních rozhodnutí, dokumentů a partnerů, které budete potřebovat.'], ['zivot-v-chorvatsku', 'Život v Chorvatsku: praktický průvodce', 'Život', 'Od pobytu a zdravotní péče až po každodenní administrativu.'], ['turisticky-pronajem', 'Turistický pronájem a kategorizace apartmánu', 'Turismus', 'Jak připravit nemovitost a administrativu pro legální pronájem.'], ['pojisteni', 'Jaké pojištění potřebujete v Chorvatsku?', 'Pojištění', 'Základní přehled pojištění nemovitosti, vozidla, zdraví a podnikání.'], ['cesko-chorvatsko', 'Podnikání mezi Českem a Chorvatskem', 'Spolupráce', 'Kde vznikají příležitosti a proč je místní partner klíčový.']] },
  },
  hr: {
    home: { eyebrow: 'Češka × Hrvatska', title: 'Vaš pouzdan partner za poslovanje, ulaganje i život u Hrvatskoj.', lead: 'Pomažemo češkim građanima, poduzetnicima i investitorima da jednostavnije ostvare svoje planove u Hrvatskoj. Povezujemo vas s provjerenim stručnjacima i vodimo kroz cijeli proces.', trust: 'Individualan pristup · lokalno znanje · provjereni partneri', categories: [['Nekretnine', 'Podrška pri kupnji i koordinacija dokumentacije.'], ['Poslovanje', 'Praktična pomoć pri ulasku na hrvatsko tržište.'], ['Administracija', 'Sigurnost u postupcima, obrascima i komunikaciji.'], ['Pouzdani partneri', 'Mreža stručnjaka za svaki korak vašeg projekta.']], introTitle: 'Manje neizvjesnosti. Više jasnih koraka.', introText: 'CROBIZ spaja poznavanje češkog i hrvatskog okruženja s osobnim vođenjem. Dobivate jednu pouzdanu kontaktnu točku, razumljivu komunikaciju i koordinaciju ljudi koje vaš plan stvarno treba.', servicesTitle: 'Podrška točno tamo gdje je trebate', whyTitle: 'Zašto baš Hrvatska?', whyText: 'Sigurna europska zemlja s eurom, stabilnim tržištem, snažnim turizmom i iznimnom kvalitetom života.', processTitle: 'Od prvog pitanja do gotovog rješenja', process: [['01', 'Uvodne konzultacije', 'Upoznajemo vaš cilj, situaciju i prioritete.'], ['02', 'Jasan plan', 'Predlažemo korake, dokumentaciju i prave stručnjake.'], ['03', 'Koordinacija', 'Povezujemo sve strane i pratimo tijek procesa.'], ['04', 'Dugoročna podrška', 'Ostajemo vaš partner i nakon završetka.']] },
    about: { eyebrow: 'O CROBIZ-u', title: 'Specijalizirano savjetovanje između Češke i Hrvatske.', lead: 'CROBIZ je specijalizirana konzultantska tvrtka za podršku češkim građanima, poduzetnicima i investitorima u Hrvatskoj.', storyTitle: 'O tvrtki CROBIZ', story: 'Osnivačica CROBIZ-a je Ivana Pisac, koja zahvaljujući izvrsnom poznavanju hrvatskog i češkog jezika te poslovnog okruženja obje zemlje pomaže klijentima u koordinaciji administrativnih i poslovnih procesa.', values: [['Dva jezika, jedno razumijevanje', 'Tečna komunikacija na hrvatskom i češkom bez nepotrebnih nesporazuma.'], ['Individualan pristup', 'Rješenje prilagođeno vašem cilju, budžetu i vremenu.'], ['Profesionalna koordinacija', 'Pregledni koraci, redovite informacije i odgovornost za komunikaciju.'], ['Dugoročni odnosi', 'Ne težimo jednokratnoj usluzi, nego partnerstvu temeljenom na povjerenju.']], networkTitle: 'Mreža provjerenih partnera diljem Hrvatske' },
    how: { eyebrow: 'Kako surađujemo', title: 'Jasan proces od prvih konzultacija do dugoročne podrške.', lead: 'Svaku suradnju gradimo na razumljivim koracima, redovitoj komunikaciji i koordinaciji odgovarajućih stručnjaka.' },
    services: { eyebrow: 'Usluge', title: 'Sveobuhvatna podrška za vaše planove u Hrvatskoj.', lead: 'Od prvog istraživanja do koordinacije konkretnog postupka. Odabiremo pravi put i povezujemo vas s potrebnim stručnjacima.', groups: [['Poslovanje u Hrvatskoj', ['Informacije o poslovanju', 'Pomoć pri osnivanju društva ili obrta', 'Administrativna podrška', 'Povezivanje s računovodstvenim servisima', 'Pomoć pri otvaranju poslovnog računa']], ['Nekretnine', ['Pomoć pri kupnji nekretnine', 'Koordinacija procesa', 'Pomoć pri dokumentaciji', 'Komunikacija sa sudionicima transakcije']], ['Administrativna podrška', ['Komunikacija s institucijama', 'Pomoć pri dokumentaciji i obrascima', 'Koordinacija postupaka', 'Objašnjenje sljedećih koraka']], ['Pravno i računovodstveno posredovanje', ['Povezivanje s odvjetnicima i javnim bilježnicima', 'Povezivanje s računovođama i poreznim savjetnicima', 'Koordinacija komunikacije']], ['Osiguranja', ['Osiguranje nekretnina', 'Osiguranje vozila i putno osiguranje', 'Zdravstvena i poslovna osiguranja']], ['Turizam', ['Pomoć pri kategorizaciji apartmana', 'Administrativna podrška', 'Pomoć pri pokretanju turističke djelatnosti']], ['Prijevodi i komunikacija', ['Hrvatski–češki i češki–hrvatski', 'Poslovna komunikacija', 'Podrška u komunikaciji s institucijama']]], disclaimerTitle: 'Važna napomena', disclaimer: 'CROBIZ ne pruža pravne niti računovodstvene usluge. Klijente povezuje s provjerenim odvjetnicima, javnim bilježnicima, računovođama i drugim stručnjacima te koordinira komunikaciju.', partners: ['Odvjetnici', 'Javni bilježnici', 'Računovođe', 'Porezni savjetnici', 'Arhitekti', 'Projektanti', 'Geodeti', 'Građevinske tvrtke', 'Agenti za nekretnine', 'Osiguravajuća društva', 'Sudski tumači'] },
    why: { eyebrow: 'Zašto Hrvatska', title: 'Stabilno europsko okruženje s iznimnim potencijalom.', lead: 'Hrvatska spaja sigurnost Europske unije, euro, snažno turističko gospodarstvo i stil života koji trajno privlači češke građane i investitore.', reasons: [['Članica Europske unije', 'Zajednički pravni i gospodarski okvir olakšava kretanje ljudi, kapitala i poslovanje.'], ['Euro kao valuta', 'Jednostavnija plaćanja, planiranje ulaganja i manji valutni rizik.'], ['Stabilno tržište', 'Predvidljivo okruženje i rastući interes stranih ulagača.'], ['Atraktivna ulaganja', 'Prilike u nekretninama, turizmu, uslugama i lokalnom poslovanju.'], ['Razvijen turizam', 'Snažna međunarodna potražnja i dugoročna prepoznatljivost destinacije.'], ['Odlična povezanost', 'Cestovne i zračne veze s Češkom tijekom cijele godine.'], ['Kvaliteta života', 'Sigurnost, priroda, klima, gastronomija i blizina mora.']], sectorsTitle: 'Prilike koje imaju smisla', sectors: ['Stambene nekretnine', 'Turistički smještaj', 'Usluge i trgovina', 'Lokalna partnerstva'] },
    faq: { eyebrow: 'Česta pitanja', title: 'Odgovori koji vam pomažu krenuti.', lead: 'Svaki slučaj je drugačiji, ali ovi odgovori pružaju osnovnu orijentaciju.', items: [['Kako kupiti nekretninu u Hrvatskoj?', 'Postupak počinje definiranjem budžeta i zahtjeva, nastavlja se provjerom nekretnine i dokumentacije, a završava ugovorom, plaćanjem i upisom vlasništva. CROBIZ koordinira komunikaciju i povezuje vas s odgovarajućim stručnjakom.'], ['Kako osnovati tvrtku?', 'Prema vašim ciljevima odabire se pravni oblik, priprema dokumentacija, provodi registracija i otvara račun. Pomažemo organizirati korake i pronaći računovođu.'], ['Koliko traje postupak?', 'Trajanje ovisi o vrsti usluge, spremnosti dokumentacije i institucijama. Nakon konzultacije dajemo realan vremenski okvir.'], ['Mogu li sve riješiti na daljinu?', 'Mnogi se koraci mogu riješiti online ili putem punomoći. Upozorit ćemo vas kada je osobna prisutnost nužna ili korisna.'], ['Na kojem jeziku komunicirate?', 'Komuniciramo na hrvatskom, češkom i engleskom te koordiniramo komunikaciju sa stručnjacima i institucijama.'], ['Radite li na području cijele Hrvatske?', 'Da. Zahvaljujući mreži partnera pomažemo klijentima u različitim dijelovima Hrvatske, prema projektu i dostupnosti stručnjaka.']] },
    contact: { eyebrow: 'Kontakt', title: 'Razgovarajmo o vašem planu.', lead: 'Ukratko nam opišite svoju situaciju. Javit ćemo se, razjasniti potrebe i predložiti najbolji sljedeći korak.', hours: 'Ponedjeljak–petak · 9:00–17:00', response: 'U pravilu odgovaramo unutar jednog radnog dana.' },
    blog: { eyebrow: 'Vodič kroz Hrvatsku', title: 'Praktične informacije za pametne odluke.', lead: 'Razumljivi članci o nekretninama, poslovanju, administraciji i životu u Hrvatskoj.', posts: [['kupnja-nekretnine', 'Kupnja nekretnine u Hrvatskoj: prvi koraci', 'Nekretnine', 'Što razjasniti prije pretrage i kako izgleda siguran proces kupnje.'], ['osnivanje-tvrtke', 'Kako osnovati tvrtku u Hrvatskoj', 'Poslovanje', 'Pregled ključnih odluka, dokumenata i partnera koji će vam trebati.'], ['zivot-u-hrvatskoj', 'Život u Hrvatskoj: praktični vodič', 'Život', 'Od boravka i zdravstva do svakodnevne administracije.'], ['turisticki-najam', 'Turistički najam i kategorizacija apartmana', 'Turizam', 'Kako pripremiti nekretninu i administraciju za legalan najam.'], ['osiguranja', 'Koja osiguranja trebate u Hrvatskoj?', 'Osiguranja', 'Pregled osiguranja nekretnina, vozila, zdravlja i poslovanja.'], ['ceska-hrvatska', 'Poslovanje između Češke i Hrvatske', 'Suradnja', 'Gdje nastaju prilike i zašto je lokalni partner važan.']] },
  },
  en: {
    home: { eyebrow: 'Czechia × Croatia', title: 'Your trusted partner for business, investment and life in Croatia.', lead: 'We help Czech citizens, entrepreneurs and investors bring their plans in Croatia to life. We connect you with trusted professionals and guide you throughout the process.', trust: 'Personal approach · local knowledge · trusted partners', categories: [['Property', 'Purchase support and document coordination.'], ['Business', 'Practical help entering the Croatian market.'], ['Administration', 'Clarity across procedures, forms and communication.'], ['Trusted partners', 'A professional network for every stage of your project.']], introTitle: 'Less uncertainty. More clear next steps.', introText: 'CROBIZ combines knowledge of the Czech and Croatian environments with personal guidance. You gain one reliable point of contact, clear communication and coordination of the right people for your plan.', servicesTitle: 'Support exactly where you need it', whyTitle: 'Why Croatia?', whyText: 'A safe European country with the euro, a stable market, strong tourism and an exceptional quality of life.', processTitle: 'From the first question to a complete solution', process: [['01', 'Initial consultation', 'We learn about your goal, situation and priorities.'], ['02', 'A clear plan', 'We define the steps, documents and specialists required.'], ['03', 'Coordination', 'We connect everyone involved and keep the process moving.'], ['04', 'Long-term support', 'We remain your partner after completion.']] },
    about: { eyebrow: 'About CROBIZ', title: 'Specialist consultancy between Czechia and Croatia.', lead: 'CROBIZ is a specialist consultancy supporting Czech citizens, entrepreneurs and investors in Croatia.', storyTitle: 'About CROBIZ', story: 'CROBIZ was founded by Ivana Pisac, whose excellent knowledge of Croatian and Czech, together with the business environments of both countries, helps clients coordinate administrative and business processes.', values: [['Two languages, shared understanding', 'Fluent communication in Czech and Croatian without unnecessary misunderstandings.'], ['Personal approach', 'A solution adapted to your goals, budget and timeline.'], ['Professional coordination', 'Clear steps, regular updates and ownership of communication.'], ['Long-term relationships', 'We aim for trusted partnerships, not one-off transactions.']], networkTitle: 'A network of trusted partners across Croatia' },
    how: { eyebrow: 'How we work', title: 'A clear process from the initial consultation to long-term support.', lead: 'Every engagement is built around clear steps, regular communication and coordination with the right professionals.' },
    services: { eyebrow: 'Services', title: 'Comprehensive support for your plans in Croatia.', lead: 'From early research to coordinating a specific procedure, we define the right path and connect you with the professionals you need.', groups: [['Business in Croatia', ['Business environment information', 'Support establishing a company or trade', 'Administrative support', 'Accounting service introductions', 'Business bank account assistance']], ['Property', ['Property purchase support', 'Process coordination', 'Document assistance', 'Communication with transaction parties']], ['Administrative support', ['Communication with institutions', 'Document and form assistance', 'Procedure coordination', 'Clear explanations of next steps']], ['Legal and accounting introductions', ['Introductions to lawyers and notaries', 'Introductions to accountants and tax advisers', 'Communication coordination']], ['Insurance', ['Property insurance', 'Vehicle and travel insurance', 'Health and business insurance']], ['Tourism', ['Apartment categorisation support', 'Administrative support', 'Help launching tourism activities']], ['Translation and communication', ['Croatian–Czech and Czech–Croatian', 'Business communication', 'Institutional communication support']]], disclaimerTitle: 'Important notice', disclaimer: 'CROBIZ does not provide legal or accounting services. We connect clients with trusted lawyers, notaries, accountants and other professionals and coordinate communication.', partners: ['Lawyers', 'Notaries', 'Accountants', 'Tax advisers', 'Architects', 'Designers', 'Surveyors', 'Construction companies', 'Property agents', 'Insurers', 'Court interpreters'] },
    why: { eyebrow: 'Why Croatia', title: 'A stable European environment with exceptional potential.', lead: 'Croatia combines the security of the European Union, the euro, a strong tourism economy and a lifestyle that continues to attract Czech citizens and investors.', reasons: [['European Union member', 'A shared legal and economic framework makes movement, investment and business easier.'], ['Euro currency', 'Simpler payments and investment planning with less currency risk.'], ['Stable market', 'A predictable environment with growing international interest.'], ['Attractive investments', 'Opportunities in property, tourism, services and local businesses.'], ['Developed tourism', 'Strong international demand and long-term destination recognition.'], ['Excellent connections', 'Road and air connections with Czechia throughout the year.'], ['Quality of life', 'Safety, nature, climate, food and proximity to the sea.']], sectorsTitle: 'Opportunities that make sense', sectors: ['Residential property', 'Tourism accommodation', 'Services and commerce', 'Local partnerships'] },
    faq: { eyebrow: 'Frequently asked questions', title: 'Answers that help you get started.', lead: 'Every case is different, but these answers provide a useful starting point.', items: [['How do I buy property in Croatia?', 'The process starts with defining your budget and requirements, continues with property and document checks, and ends with the contract, payment and ownership registration. CROBIZ coordinates communication and introduces the appropriate professional.'], ['How do I establish a company?', 'We help identify a suitable legal form, organise the documentation, registration, bank account and accounting relationship.'], ['How long does the process take?', 'Timing depends on the service, document readiness and institutions involved. We provide a realistic timeline after the initial consultation.'], ['Can everything be handled remotely?', 'Many steps can be completed online or through a power of attorney. We will tell you when personal presence is necessary or beneficial.'], ['Which languages do you speak?', 'We communicate in Czech, Croatian and English and coordinate communication with specialists and institutions.'], ['Do you work throughout Croatia?', 'Yes. Our partner network allows us to support projects in different parts of Croatia, subject to the project and specialist availability.']] },
    contact: { eyebrow: 'Contact', title: 'Let’s talk about your plans.', lead: 'Tell us briefly about your situation. We will get back to clarify your needs and suggest the best next step.', hours: 'Monday–Friday · 9:00–17:00', response: 'We usually respond within one working day.' },
    blog: { eyebrow: 'Croatia guide', title: 'Practical information for confident decisions.', lead: 'Clear articles about property, business, administration and life in Croatia.', posts: [['buying-property', 'Buying property in Croatia: first steps', 'Property', 'What to clarify before searching and how a safe purchase process works.'], ['starting-company', 'How to establish a company in Croatia', 'Business', 'The key decisions, documents and partners you will need.'], ['living-croatia', 'Living in Croatia: a practical guide', 'Lifestyle', 'From residence and healthcare to everyday administration.'], ['tourism-rental', 'Tourism rentals and apartment categorisation', 'Tourism', 'Preparing your property and administration for legal rentals.'], ['insurance-croatia', 'Which insurance do you need in Croatia?', 'Insurance', 'An overview of property, vehicle, health and business insurance.'], ['czech-croatian-business', 'Business between Czechia and Croatia', 'Partnership', 'Where opportunities arise and why a local partner matters.']] },
  },
}

export const useSiteContent = () => {
  const { locale } = useI18n()
  return computed(() => content[locale.value] || content.cs)
}
