<script setup>
const site = useSiteContent(); const { t } = useI18n(); const localePath = useLocalePath(); const images = useSiteImages(); usePageSeo('contact')
const submitForm = (event) => {
  const data = new FormData(event.currentTarget)
  const subject = `CROBIZ · ${data.get('topic')} · ${data.get('name')}`
  const body = `${data.get('message')}\n\n${data.get('name')}\n${data.get('email')}\n${data.get('phone') || ''}`
  window.location.href = `mailto:info@crobiz.cz?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
}
</script>
<template><div><PageHero :eyebrow="site.contact.eyebrow" :title="site.contact.title" :lead="site.contact.lead"/><section class="section" style="padding-top:20px"><div class="container contact-grid"><div><p class="eyebrow">CROBIZ</p><h2 class="section-title">{{ t('footer.contact') }}</h2><div class="contact-details"><div class="contact-card"><small>E-mail</small><a href="mailto:info@crobiz.cz">info@crobiz.cz</a></div><div class="contact-card"><small>Direct</small><a href="mailto:ivana.pisac@crobiz.info">ivana.pisac@crobiz.info</a></div><div class="contact-card"><small>Phone · WhatsApp</small><span>—</span></div><div class="contact-card"><small>Working hours</small><span>{{ site.contact.hours }}</span></div></div><p class="section-copy">{{ site.contact.response }}</p></div><form class="contact-form" @submit.prevent="submitForm"><div class="form-field"><label for="name">{{ t('form.name') }}</label><input id="name" name="name" autocomplete="name" required></div><div class="form-field"><label for="email">{{ t('form.email') }}</label><input id="email" name="email" type="email" autocomplete="email" required></div><div class="form-field"><label for="phone">{{ t('form.phone') }}</label><input id="phone" name="phone" type="tel" autocomplete="tel"></div><div class="form-field"><label for="topic">{{ t('form.topic') }}</label><select id="topic" name="topic"><option v-for="key in ['general','business','property','admin','tourism']" :key="key">{{ t(`form.topics.${key}`) }}</option></select></div><div class="form-field form-field--full"><label for="message">{{ t('form.message') }}</label><textarea id="message" name="message" required></textarea></div><label class="form-consent"><input type="checkbox" required><span>{{ t('form.privacy') }} <NuxtLink :to="localePath('/privacy')">{{ t('footer.privacy') }}</NuxtLink></span></label><button class="button button--primary" type="submit">{{ t('actions.send') }}</button></form></div><div class="container"><ImagePlaceholder class="map-placeholder" :label="t('common.photoCoast')" :src="images.lifestyle"/></div></section></div></template>
