<script setup>
const { locale, t } = useI18n()
const { openSettings } = useConsent()
const copy = computed(() => ({
  cs:{title:'Zásady používání cookies',lead:'Jak CROBIZ používá lokální úložiště, cookies a volitelnou analytiku.',updated:'Aktualizováno: 17. července 2026',intro:'Při první návštěvě je analytika vypnutá. Google Analytics se nestáhne ani nespustí, dokud jej výslovně nepovolíte.',necessary:'Nezbytné úložiště',necessaryText:'Je nutné pro uložení vašeho souhlasu, jazyka a bezpečné fungování webu. Nelze je vypnout prostřednictvím panelu.',analytics:'Analytika',analyticsText:'Po souhlasu může web načíst Google Analytics 4, abychom získali souhrnné informace o návštěvnosti. Reklamní úložiště, personalizace a Google Signals zůstávají vypnuté.',change:'Volbu můžete kdykoli změnit tlačítkem Nastavení cookies v patičce. Odmítnutí neomezuje přístup k webu.',headers:['Kategorie','Technologie','Účel','Doba'],rows:[['Nezbytné','crobiz-consent · localStorage','Volba, datum a verze souhlasu','Do změny nebo vymazání'],['Nezbytné','Nastavení jazyka','Zapamatování zvoleného jazyka','Podle nastavení prohlížeče'],['Analytika','_ga · _ga_*','Rozlišení návštěv a relací v GA4','Až 2 roky; pouze po souhlasu']]},
  sk:{title:'Zásady používania cookies',lead:'Ako CROBIZ používa lokálne úložisko, cookies a voliteľnú analytiku.',updated:'Aktualizované: 17. júla 2026',intro:'Pri prvej návšteve je analytika vypnutá. Google Analytics sa nestiahne ani nespustí, kým ho výslovne nepovolíte.',necessary:'Nevyhnutné úložisko',necessaryText:'Je potrebné na uloženie vášho súhlasu, jazyka a bezpečné fungovanie webu. Nemožno ho vypnúť prostredníctvom panela.',analytics:'Analytika',analyticsText:'Po udelení súhlasu môže web načítať Google Analytics 4, aby sme získali súhrnné informácie o návštevnosti. Reklamné úložisko, personalizácia a Google Signals zostávajú vypnuté.',change:'Voľbu môžete kedykoľvek zmeniť tlačidlom Nastavenia cookies v pätičke. Odmietnutie neobmedzuje prístup k webu.',headers:['Kategória','Technológia','Účel','Doba'],rows:[['Nevyhnutné','crobiz-consent · localStorage','Voľba, dátum a verzia súhlasu','Do zmeny alebo vymazania'],['Nevyhnutné','Nastavenie jazyka','Zapamätanie zvoleného jazyka','Podľa nastavení prehliadača'],['Analytika','_ga · _ga_*','Rozlíšenie návštev a relácií v GA4','Až 2 roky; iba po súhlase']]},
  hr:{title:'Politika kolačića',lead:'Kako CROBIZ koristi lokalnu pohranu, kolačiće i neobaveznu analitiku.',updated:'Ažurirano: 17. srpnja 2026.',intro:'Pri prvom posjetu analitika je isključena. Google Analytics se ne preuzima niti pokreće dok ga izričito ne dopustite.',necessary:'Nužna pohrana',necessaryText:'Potrebna je za spremanje odabira privole, jezika i sigurno funkcioniranje stranice. Ne može se isključiti u postavkama.',analytics:'Analitika',analyticsText:'Nakon privole stranica može učitati Google Analytics 4 radi zbirnih podataka o posjećenosti. Oglašivačka pohrana, personalizacija i Google Signals ostaju isključeni.',change:'Odabir možete promijeniti putem gumba Postavke kolačića u podnožju. Odbijanje ne ograničava pristup stranici.',headers:['Kategorija','Tehnologija','Svrha','Trajanje'],rows:[['Nužno','crobiz-consent · localStorage','Odabir, datum i verzija privole','Do promjene ili brisanja'],['Nužno','Postavka jezika','Pamćenje odabranog jezika','Prema postavkama preglednika'],['Analitika','_ga · _ga_*','Razlikovanje posjeta i sesija u GA4','Do 2 godine; samo nakon privole']]},
  en:{title:'Cookie policy',lead:'How CROBIZ uses local storage, cookies and optional analytics.',updated:'Updated: 17 July 2026',intro:'Analytics is disabled on the first visit. Google Analytics is neither downloaded nor executed until you explicitly allow it.',necessary:'Necessary storage',necessaryText:'Required to remember your consent choice, language and provide secure website functionality. It cannot be disabled in the preference panel.',analytics:'Analytics',analyticsText:'After consent, the website may load Google Analytics 4 to obtain aggregated usage information. Advertising storage, personalisation and Google Signals remain disabled.',change:'You can change your choice at any time through Cookie settings in the footer. Refusing does not restrict access to the website.',headers:['Category','Technology','Purpose','Duration'],rows:[['Necessary','crobiz-consent · localStorage','Consent choice, date and policy version','Until changed or cleared'],['Necessary','Language preference','Remembering the selected language','According to browser settings'],['Analytics','_ga · _ga_*','Distinguishing visits and sessions in GA4','Up to 2 years; consent only']]},
})[locale.value])
useCustomPageSeo({ section:'cookies', title:() => copy.value.title, description:() => copy.value.lead })
</script>

<template>
  <div><section class="section surface-sand"><div class="container legal-content"><p class="eyebrow">{{ t('footer.legal') }}</p><h1 class="page-title">{{ copy.title }}</h1><p class="page-lead">{{ copy.lead }}</p><p class="legal-updated">{{ copy.updated }}</p></div></section><section class="section"><div class="container legal-content"><p>{{ copy.intro }}</p><h2>{{ copy.necessary }}</h2><p>{{ copy.necessaryText }}</p><h2>{{ copy.analytics }}</h2><p>{{ copy.analyticsText }}</p><div class="legal-table-wrap"><table class="legal-table"><thead><tr><th v-for="item in copy.headers" :key="item">{{ item }}</th></tr></thead><tbody><tr v-for="row in copy.rows" :key="row[1]"><td v-for="cell in row" :key="cell">{{ cell }}</td></tr></tbody></table></div><p class="legal-note">{{ copy.change }}</p><div class="button-row"><button class="button button--primary" type="button" @click="openSettings">{{ t('footer.cookieSettings') }}</button></div></div></section></div>
</template>
